### ISSUE TITLE
support for exclude (or include) flag

### ISSUE THREAD

**Issue by bstpierre** [tonybaloney/retox#11]
I had intended to open an issue to add support for multiple exclude flags, but I noticed that you recently changed the test to only explicitly watch `.py`.

I'd prefer to have exclude functionality because another project I'm working on runs tox checks against some .rst and other files, and I'd generally rather have retox run the checks even when non-python files change (e.g. .pylintrc, etc).

If it's something you'd accept I can work up a PR to:

- add `--exclude=regex` argument
- change `get_hashes()` to take an exclude=regex arg

**Comment by tonybaloney** [comment]
Absolutely. I just changed it to an include because people were just assigning the root project directory and it would run continuously (because the tox path, and the log files were included)
It’s a temporary workaround until a better solution is found. A PR would be great. You’d need to add the argument to the plugin sub module

**Comment by tonybaloney** [comment]
Closing as resolved
